/*
 * CBT & Training System API
 *
 * API untuk sistem CBT dengan role Admin, Pengajar, dan Siswa. (Revised for production readiness)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ErrorResponse struct {

	Code string `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}
