/*
 * CBT & Training System API
 *
 * API untuk sistem CBT dengan role Admin, Pengajar, dan Siswa. (Revised for production readiness)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type HasilUjian struct {

	ExamId int32 `json:"examId,omitempty"`

	Score float32 `json:"score,omitempty"`

	Details []HasilUjianDetailsInner `json:"details,omitempty"`
}
