/*
 * CBT & Training System API
 *
 * API untuk sistem CBT dengan role Admin, Pengajar, dan Siswa. (Revised for production readiness)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserInput struct {

	Name string `json:"name"`

	Email string `json:"email"`

	Password string `json:"password"`

	Role string `json:"role"`
}
