/*
 * CBT & Training System API
 *
 * API untuk sistem CBT dengan role Admin, Pengajar, dan Siswa. (Revised for production readiness)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PengajarKelasGet200Response struct {

	CurrentPage int32 `json:"currentPage,omitempty"`

	TotalPages int32 `json:"totalPages,omitempty"`

	TotalItems int32 `json:"totalItems,omitempty"`

	Limit int32 `json:"limit,omitempty"`

	Data []Kelas `json:"data,omitempty"`
}
