/*
 * CBT & Training System API
 *
 * API untuk sistem CBT dengan role Admin, Pengajar, dan Siswa. (Revised for production readiness)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserUpdateInput struct {

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	// Isi hanya jika ingin mengubah password
	Password string `json:"password,omitempty"`

	Role string `json:"role,omitempty"`
}
