/*
 * CBT & Training System API
 *
 * API untuk sistem CBT dengan role Admin, Pengajar, dan Siswa. (Revised for production readiness)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UjianDetail struct {

	Id int32 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Questions []UjianDetailQuestionsInner `json:"questions,omitempty"`
}
