/*
 * CBT & Training System API
 *
 * API untuk sistem CBT dengan role Admin, Pengajar, dan Siswa. (Revised for production readiness)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobStatusResponse struct {

	JobId string `json:"jobId,omitempty"`

	Status string `json:"status,omitempty"`

	Progress float32 `json:"progress,omitempty"`

	Result JobStatusResponseResult `json:"result,omitempty"`

	Error *string `json:"error,omitempty"`
}
