/*
 * CBT & Training System API
 *
 * API untuk sistem CBT dengan role Admin, Pengajar, dan Siswa. (Revised for production readiness)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UjianDetailQuestionsInner struct {

	Id int32 `json:"id,omitempty"`

	Type string `json:"type,omitempty"`

	Text string `json:"text,omitempty"`

	Options []string `json:"options,omitempty"`
}
