# Stage 1: Build static files
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package.json and install dependencies
COPY FE/package*.json ./
RUN npm install

# Copy source code
COPY FE/. .

# Build aplication
RUN npm run build

# Stage 2: Serve using Nginx
FROM nginx:stable-alpine

# Copy static file from dist
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80 (default nginx)
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]